"""MACR v0.7 semantic contract family."""

from .contracts import (
    ArtifactRole,
    BindingKind,
    ClaimStatus,
    ExternalSemanticBinding,
    ResolutionStatus,
    SemanticEvent,
    SemanticEventType,
    SemanticLifecycleStatus,
    SemanticNode,
    SemanticNodeType,
    SemanticPatch,
    SemanticProfileRef,
    SemanticProvenance,
    SemanticRelation,
    SemanticRelationType,
)
from .graph import (
    SEMANTIC_GRAPH_HEAD_SCHEMA_VERSION,
    SEMANTIC_GRAPH_REVISION_SCHEMA_VERSION,
    SemanticGraphHead,
    SemanticGraphRevision,
    calculate_graph_digest,
)
from .database import SemanticSchema
from .registry import SEMANTIC_REGISTRY_SCHEMA_VERSION, SemanticRegistry
from .store import SemanticStore
from .service import SemanticProposalRecord, SemanticProposalService
from .commit import (
    SemanticAttachReceipt,
    SemanticCommitReceipt,
    SemanticCommitService,
    ownership_permit_digest,
)
from .patch import (
    SEMANTIC_COMMIT_REQUEST_SCHEMA_VERSION,
    SEMANTIC_PROPOSAL_SCHEMA_VERSION,
    CompiledSemanticPatch,
    SemanticCommitRequest,
    SemanticPatchCompiler,
    SemanticPatchProposalRequest,
)
from .projection import (
    MAX_PROJECTION_NODES,
    MAX_PROJECTION_RELATIONS,
    SEMANTIC_CONTEXT_PROJECTION_SCHEMA_VERSION,
    SEMANTIC_CONTEXT_REQUEST_SCHEMA_VERSION,
    SEMANTIC_PROJECTION_PROFILE_SCHEMA_VERSION,
    SemanticContextProjection,
    SemanticContextProjector,
    SemanticContextRequest,
    SemanticProjectionProfile,
)

__all__ = [
    "ArtifactRole",
    "BindingKind",
    "ClaimStatus",
    "ExternalSemanticBinding",
    "ResolutionStatus",
    "SemanticEvent",
    "SemanticEventType",
    "SemanticLifecycleStatus",
    "SemanticGraphHead",
    "SemanticGraphRevision",
    "SemanticNode",
    "SemanticNodeType",
    "SemanticPatch",
    "SemanticPatchCompiler",
    "SemanticPatchProposalRequest",
    "SemanticProfileRef",
    "SemanticProvenance",
    "SemanticRelation",
    "SemanticRelationType",
    "SemanticRegistry",
    "SemanticSchema",
    "SemanticStore",
    "SemanticProposalRecord",
    "SemanticProposalService",
    "SemanticCommitRequest",
    "SemanticAttachReceipt",
    "SemanticCommitReceipt",
    "SemanticCommitService",
    "SemanticContextProjection",
    "SemanticContextProjector",
    "SemanticContextRequest",
    "SemanticProjectionProfile",
    "CompiledSemanticPatch",
    "SEMANTIC_GRAPH_HEAD_SCHEMA_VERSION",
    "SEMANTIC_GRAPH_REVISION_SCHEMA_VERSION",
    "SEMANTIC_REGISTRY_SCHEMA_VERSION",
    "SEMANTIC_COMMIT_REQUEST_SCHEMA_VERSION",
    "SEMANTIC_PROPOSAL_SCHEMA_VERSION",
    "SEMANTIC_CONTEXT_PROJECTION_SCHEMA_VERSION",
    "SEMANTIC_CONTEXT_REQUEST_SCHEMA_VERSION",
    "SEMANTIC_PROJECTION_PROFILE_SCHEMA_VERSION",
    "MAX_PROJECTION_NODES",
    "MAX_PROJECTION_RELATIONS",
    "calculate_graph_digest",
    "ownership_permit_digest",
]
