-- Independent schema-7 source fixture generated by main@f806fdb0069fcaad28ec1d20f7fa0fc85e8b405e.
-- It is deliberately not constructed by the schema-8 implementation under test.
BEGIN TRANSACTION;
CREATE TABLE authority_epoch (
    singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
    epoch INTEGER NOT NULL,
    state TEXT NOT NULL,
    reason_digest TEXT,
    updated_at TEXT NOT NULL
);
INSERT INTO authority_epoch VALUES(1,0,'open',NULL,'1970-01-01T00:00:00+00:00');
CREATE TABLE batch_authorities (
    authority_id TEXT PRIMARY KEY,
    body_json TEXT NOT NULL,
    body_sha256 TEXT NOT NULL UNIQUE,
    scope_json TEXT NOT NULL,
    scope_sha256 TEXT NOT NULL,
    plan_digest TEXT NOT NULL,
    revision INTEGER NOT NULL,
    issued_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked_at TEXT,
    UNIQUE(plan_digest, revision)
);
CREATE TABLE candidate_captures (
    capture_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL UNIQUE,
    provider_id TEXT NOT NULL,
    answer_sha256 TEXT NOT NULL,
    answer_bytes INTEGER NOT NULL,
    relative_path TEXT NOT NULL,
    task_digest TEXT NOT NULL,
    approval_digest TEXT,
    captured_at TEXT NOT NULL
);
CREATE TABLE dispatch_authorities (
    authority_id TEXT PRIMARY KEY,
    source_kind TEXT NOT NULL,
    source_id TEXT NOT NULL,
    body_json TEXT NOT NULL,
    body_sha256 TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK(revision >= 1),
    epoch INTEGER NOT NULL,
    scope_json TEXT NOT NULL,
    issued_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked_at TEXT,
    UNIQUE(source_kind, source_id, revision)
);
CREATE TABLE dispatch_leases (
    resource_key TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    fencing_token INTEGER NOT NULL,
    acquired_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE TABLE events (
    sequence INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL UNIQUE,
    run_id TEXT REFERENCES runs(run_id),
    event_type TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    source_sha256 TEXT,
    source_line INTEGER
);
INSERT INTO events VALUES(
    1,
    '22222222-2222-4222-8222-222222222222',
    '11111111-1111-4111-8111-111111111111',
    'provider.dispatch_requested',
    '2026-09-10T00:00:00+00:00',
    '{"fixture":"schema7-main-f806fdb"}',
    NULL,
    NULL
);
CREATE TABLE fencing_counter (
    singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
    value INTEGER NOT NULL
);
INSERT INTO fencing_counter VALUES(1,0);
CREATE TABLE legacy_quarantine (
    source_sha256 TEXT NOT NULL REFERENCES legacy_sources(source_sha256),
    line_number INTEGER NOT NULL,
    raw_sha256 TEXT NOT NULL,
    raw_bytes BLOB NOT NULL,
    error_code TEXT NOT NULL,
    PRIMARY KEY (source_sha256, line_number)
);
CREATE TABLE legacy_sources (
    source_sha256 TEXT PRIMARY KEY,
    source_bytes INTEGER NOT NULL,
    expected_count INTEGER,
    observed_count INTEGER NOT NULL,
    valid_count INTEGER NOT NULL,
    corrupt_count INTEGER NOT NULL,
    duplicate_count INTEGER NOT NULL,
    imported_count INTEGER NOT NULL,
    complete INTEGER NOT NULL,
    imported_at TEXT NOT NULL
);
CREATE TABLE materializations (
    materialization_id TEXT PRIMARY KEY,
    capture_id TEXT NOT NULL REFERENCES candidate_captures(capture_id),
    state TEXT NOT NULL,
    output_sha256 TEXT NOT NULL,
    output_bytes INTEGER NOT NULL,
    relative_path TEXT,
    target_path_sha256 TEXT,
    transformer_version TEXT,
    builder_origin_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE TABLE plan_queue_batches (
    plan_digest TEXT PRIMARY KEY,
    authority_id TEXT NOT NULL REFERENCES batch_authorities(authority_id),
    authority_digest TEXT NOT NULL,
    authority_revision INTEGER NOT NULL,
    aggregate_cost_ceiling_usd REAL NOT NULL
        CHECK(aggregate_cost_ceiling_usd >= 0),
    authorized_dispatchers_json TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    members_sha256 TEXT NOT NULL,
    enqueued_at TEXT NOT NULL
);
CREATE TABLE plan_queue_members (
    member_id TEXT PRIMARY KEY,
    plan_digest TEXT NOT NULL REFERENCES plan_queue_batches(plan_digest),
    ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
    member_digest TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    route_id TEXT NOT NULL,
    role_digest TEXT NOT NULL,
    privacy TEXT NOT NULL,
    context_class TEXT NOT NULL,
    cost_ceiling_usd REAL NOT NULL CHECK(cost_ceiling_usd >= 0),
    state TEXT NOT NULL CHECK(state IN (
        'queued', 'claimed', 'completed', 'failed',
        'reconciliation_required'
    )),
    lease_holder TEXT,
    fencing_token INTEGER,
    lease_expires_at TEXT,
    attempts INTEGER NOT NULL CHECK(attempts = 0 OR attempts = 1),
    terminal_at TEXT,
    terminal_evidence_digest TEXT,
    observed_cost_usd REAL CHECK(
        observed_cost_usd IS NULL OR observed_cost_usd >= 0
    ),
    provider_tier_binding_digest TEXT,
    UNIQUE(plan_digest, ordinal),
    UNIQUE(plan_digest, member_digest)
);
CREATE TABLE plan_target_claims (
    plan_digest TEXT NOT NULL,
    target_key TEXT NOT NULL,
    member_id TEXT NOT NULL REFERENCES plan_queue_members(member_id),
    alternative_group TEXT,
    materialize_automatically INTEGER NOT NULL
        CHECK(materialize_automatically IN (0, 1)),
    PRIMARY KEY(plan_digest, target_key, member_id)
);
CREATE TABLE runs (
    run_id TEXT PRIMARY KEY,
    dispatch_event_id TEXT NOT NULL UNIQUE,
    terminal_event_id TEXT UNIQUE,
    state TEXT NOT NULL,
    started_at TEXT NOT NULL,
    terminal_at TEXT
);
INSERT INTO runs VALUES(
    '11111111-1111-4111-8111-111111111111',
    '22222222-2222-4222-8222-222222222222',
    NULL,
    'dispatched',
    '2026-09-10T00:00:00+00:00',
    NULL
);
CREATE TABLE schema_meta (
    component TEXT PRIMARY KEY,
    version INTEGER NOT NULL
);
INSERT INTO schema_meta VALUES('runtime',7);
CREATE TABLE target_path_leases (
    lease_id TEXT PRIMARY KEY,
    repository_id TEXT NOT NULL,
    target_key TEXT NOT NULL,
    plan_digest TEXT NOT NULL,
    member_digest TEXT NOT NULL,
    alternative_group TEXT,
    materialize_automatically INTEGER NOT NULL
        CHECK(materialize_automatically IN (0, 1)),
    state TEXT NOT NULL CHECK(state IN (
        'active', 'released', 'reconciliation_required'
    )),
    fencing_token INTEGER NOT NULL,
    acquired_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    released_at TEXT,
    reconciliation_evidence_digest TEXT,
    UNIQUE(repository_id, target_key, plan_digest, member_digest)
);
CREATE UNIQUE INDEX events_one_dispatch_per_run
    ON events(run_id)
    WHERE event_type = 'provider.dispatch_requested';
CREATE INDEX plan_queue_claimable
    ON plan_queue_members(state, plan_digest, ordinal);
CREATE INDEX plan_queue_expiring
    ON plan_queue_members(state, lease_expires_at);
CREATE INDEX target_path_active
    ON target_path_leases(repository_id, target_key, state);
COMMIT;
